const branches = [
  {
    code_branch: "DIA_DEVOWFS_TS",
    groups: [
      {
        code_group: "DEV203",
        code_branch: "DIA_DEVOWFS_TS",
        modules_open: [
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_presential: 5,
            formateur: "Ahmed Naim",
            salle: "INFO1",
            type: "presential",
          },
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_syn: 5,
            formateur: "Ahmed Naim",
            salle: "Teams",
            type: "à distance",
          },
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_presential: 5,
            formateur: "Ahmed Naim",
            salle: "INFO1",
            type: "presential",
          },
          {
            code_module: "M204",
            label: "base de donnée",
            nbr_hours_in_week_presential: 5,
            formateur: "ELKANDOUSSI",
            salle: "INFO2",
            type: "presential",
          },
          {
            code_module: "M204",
            label: "base de donnée",
            nbr_hours_in_week_syn: 2.5,
            formateur: "ELKANDOUSSI",
            salle: "Teams",
            type: "à distance",
          },
          {
            code_module: "M206",
            label: "français",
            nbr_hours_in_week_presential: 2.5,
            formateur: "prof fr",
            salle: "INFO3",
            type: "presential",
          },
          {
            code_module: "M207",
            label: "anglais",
            nbr_hours_in_week_presential: 2.5,
            formateur: "prof en",
            salle: "INFO4",
            type: "presential",
          },
        ],
      },
      {
        code_group: "DEV202",
        code_branch: "DIA_DEVOWFS_TS",
        modules_open: [
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_presential: 5,
            formateur: "Ahmed Naim",
            salle: "INFO1",
            type: "presential",
          },
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_syn: 5,
            formateur: "Ahmed Naim",
            salle: "Teams",
            type: "à distance",
          },
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_presential: 5,
            formateur: "Ahmed Naim",
            salle: "INFO1",
            type: "presential",
          },
          {
            code_module: "M204",
            label: "base de donnée",
            nbr_hours_in_week_presential: 5,
            formateur: "ELKANDOUSSI",
            salle: "INFO2",
            type: "presential",
          },
          {
            code_module: "M204",
            label: "base de donnée",
            nbr_hours_in_week_syn: 2.5,
            formateur: "ELKANDOUSSI",
            salle: "Teams",
            type: "à distance",
          },
          {
            code_module: "M206",
            label: "français",
            nbr_hours_in_week_presential: 2.5,
            formateur: "prof fr",
            salle: "INFO3",
            type: "presential",
          },
          {
            code_module: "M207",
            label: "anglais",
            nbr_hours_in_week_presential: 2.5,
            formateur: "prof en",
            salle: "INFO4",
            type: "presential",
          },
        ],
      },
      {
        code_group: "DEV201",
        code_branch: "DIA_DEVOWFS_TS",
        modules_open: [
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_presential: 5,
            formateur: "Ahmed Naim",
            salle: "INFO1",
            type: "presential",
          },
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_syn: 5,
            formateur: "Ahmed Naim",
            salle: "Teams",
            type: "à distance",
          },
          {
            code_module: "M202",
            label: "Approch agile",
            nbr_hours_in_week_presential: 5,
            formateur: "Ahmed Naim",
            salle: "INFO1",
            type: "presential",
          },
          {
            code_module: "M204",
            label: "base de donnée",
            nbr_hours_in_week_presential: 5,
            formateur: "ELKANDOUSSI",
            salle: "INFO2",
            type: "presential",
          },
          {
            code_module: "M204",
            label: "base de donnée",
            nbr_hours_in_week_syn: 2.5,
            formateur: "ELKANDOUSSI",
            salle: "Teams",
            type: "à distance",
          },
          {
            code_module: "M206",
            label: "français",
            nbr_hours_in_week_presential: 2.5,
            formateur: "prof fr",
            salle: "INFO3",
            type: "presential",
          },
          {
            code_module: "M207",
            label: "anglais",
            nbr_hours_in_week_presential: 2.5,
            formateur: "prof en",
            salle: "INFO4",
            type: "presential",
          },
        ],
      },
    ],
  },
];

module.exports = branches;
